### ISSUE TITLE
Comportamiento raro en multisite

### ISSUE THREAD

**Issue by maxisosa** [macr1408/Woocommerce-Mercadopago-Gateway#1]
Una vez que se activa y configura, no se puede desactivar el método de pago ni se puede editar el nombre del mismo desde --> /wp-admin/admin.php?page=wc-settings&tab=checkout

Testeado con WP 5.3.2 en modo multisite.

**Comment by macr1408** [comment]
Corregido por #2

Gracias por reportarlo
